# Generated by Django 5.2.4 on 2025-07-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelryitem',
            name='stock_quantity',
        ),
    ]
