# Generated by Django 5.2.4 on 2025-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notices_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='notice_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('notice', 'Notice'), ('price change', 'Price Change')], default='info', max_length=20),
        ),
    ]
